{
 "title": "CrateDB Monitoring",
 "description": "CrateDB cluster monitoring, including application-specific and general host-level metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data source", "query": "prometheus" },
   {
    "name": "cratedb_nodes",
    "label": "CrateDB nodes",
    "query": {
     "query": "crate_node{name=\"shard_stats\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Welcome!",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://srv.demo.crate.io/CrateDB_White.png\" width=\"200\">\n<br />\n<br />\n\nWelcome to this CrateDB monitoring dashboard! The dashboard covers essential CrateDB and operating system metrics to help you getting started.\n\nTo learn more about setting up a full monitoring stack based on Prometheus and Grafana, please [refer to our tutorial](https://community.crate.io/t/monitoring-an-on-premises-cratedb-cluster-with-prometheus-and-grafana/1236)."
   }
  },
  { "title": "Operating System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Load (1 minute average)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=~\"${cratedb_nodes}:[0-9]+\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{instance=~\"${cratedb_nodes}:[0-9]+\",mode=\"idle\"}[$__rate_interval])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - ((avg_over_time(node_memory_MemFree_bytes{instance=~\"${cratedb_nodes}:[0-9]+\"}[$__rate_interval]) + avg_over_time(node_memory_Cached_bytes{instance=~\"${cratedb_nodes}:[0-9]+\"}[$__rate_interval]) + avg_over_time(node_memory_Buffers_bytes{instance=~\"${cratedb_nodes}:[0-9]+\"}[$__rate_interval])) / avg_over_time(node_memory_MemTotal_bytes{instance=~\"${cratedb_nodes}:[0-9]+\"}[$__rate_interval])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Read/Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=~\"${cratedb_nodes}:[0-9]+\"}[$__rate_interval]) / rate(node_disk_reads_completed_total{instance=~\"${cratedb_nodes}:[0-9]+\"}[$__rate_interval]) * 100",
     "legendFormat": "Reads: {{instance}} {{device}}"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total[$__rate_interval]) / rate(node_disk_writes_completed_total[$__rate_interval]) * 100",
     "legendFormat": "Writes: {{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Used Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=~\"${cratedb_nodes}:[0-9]+\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"${cratedb_nodes}:[0-9]+\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "{{instance}} {{device}} (mountpoint: {{mountpoint}})"
    }
   ]
  },
  {
   "title": "Allocated File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"${cratedb_nodes}:[0-9]+\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Read/Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=~\"${cratedb_nodes}:[0-9]+\"}[$__rate_interval])",
     "legendFormat": "Read: {{instance}} {{device}}"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=~\"${cratedb_nodes}:[0-9]+\"}[$__rate_interval])",
     "legendFormat": "Write: {{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"${cratedb_nodes}:[0-9]+\",device=\"eth0\"}[$__rate_interval])",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"${cratedb_nodes}:[0-9]+\",device=\"eth0\"}[$__rate_interval])",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  { "title": "CrateDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Queries Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(crate_query_total_count{instance=~\"${cratedb_nodes}:[0-9]+\"}[$__rate_interval])) by (query)",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Average Query Duration (over the last 1 min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(crate_query_sum_of_durations_millis{instance=~\"${cratedb_nodes}:[0-9]+\"}[$__rate_interval])) by (query)\n/\nsum(rate(crate_query_total_count{instance=~\"${cratedb_nodes}:[0-9]+\"}[$__rate_interval])) by (query)",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Query Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(crate_query_failed_count{instance=~\"${cratedb_nodes}:[0-9]+\"}[$__rate_interval])) by (query)",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=~\"${cratedb_nodes}:[0-9]+\"}) by (instance, area)",
     "legendFormat": "{{area}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=~\"${cratedb_nodes}:[0-9]+\",area=\"heap\"} / jvm_memory_bytes_max{instance=~\"${cratedb_nodes}:[0-9]+\",area=\"heap\"}",
     "legendFormat": "{{__name__}} - {{node_name}}"
    }
   ]
  },
  {
   "title": "Circuit Breaker Memory In Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(crate_circuitbreakers{instance=~\"${cratedb_nodes}:[0-9]+\",property=\"used\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Thread Pool Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(crate_threadpools{instance=~\"${cratedb_nodes}:[0-9]+\",property=\"queueSize\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage Collector Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_count{instance=~\"${cratedb_nodes}:[0-9]+\"}[$__rate_interval])) by (instance, gc)",
     "legendFormat": "{{gc}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Global Translog Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "global_translog", "legendFormat": "size uncommitted" }
   ]
  },
  {
   "title": "Shard Distribution Per Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "targets": [
    { "expr": "shard_distribution", "legendFormat": "{{node_name}}" }
   ]
  },
  {
   "title": "Thread Pool Rejected Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 52 },
   "targets": [
    {
     "expr": "sum(crate_threadpools{instance=~\"${cratedb_nodes}:[0-9]+\",property=\"rejected\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shard Checkpoints Delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 52 },
   "targets": [
    { "expr": "checkpoints", "legendFormat": "maximum checkpoint delta" }
   ]
  }
 ]
}